### ISSUE TITLE
Need the ability to "update" a simulation

### ISSUE THREAD

**Issue by Avi-Kenny** [Avi-Kenny/simba#18]
This is a big one. Need to get this to work with all parallelization modes and need proper error handling. "Updating" a simulation could mean adding new replicates (with new methods, new creators, new levels, etc.). It probably does not mean adding new "evaluation metrics" (e.g. calculate bias in addition to MSE), since that is as simple as changing the summary() code.

**Comment by cwolock** [comment]
Basic functionality has been added. Unit tests and error handling still needed

**Comment by cwolock** [comment]
Unit tests added
