### ISSUE TITLE
Systematically go through code and add more error handling

### ISSUE THREAD

**Issue by Avi-Kenny** [Avi-Kenny/simba#25]
- get(): make sure variable names are valid
- summary(): use sim_obj$internals$run_state to guide error messages
- set_levels(): make sure only a list of key-value pairs is passed (although anything can be a "value")
- add_script(): Currently throws an uncaught error if there are NULL values in the list
- run(): Need to throw errors if incorrectly-formatted result is returned by the simulation script. For example, something that is not a list, or a list of the form list("result"=NULL) !!!!! Goes with Issue #21 
- etc.

**Comment by cwolock** [comment]
get() variable name error handling added

**Comment by cwolock** [comment]
summary() already uses run_state to throw errors for not-run or all-errors sims

**Comment by cwolock** [comment]
set_levels now requires a named list (i.e., key-value pairs)

**Comment by Avi-Kenny** [comment]
All done except for issue with run() that is being added to #21
