### ISSUE TITLE
Finish the summary() function

### ISSUE THREAD

**Issue by Avi-Kenny** [Avi-Kenny/simba#26]
Need to add other metrics (e.g. median, mode, etc.) and error handling throughout. Need to document this thoroughly.

**Comment by Avi-Kenny** [comment]
@cwolock what's the current state of summary()? Is it basically done and all we need to do is create the docs?

**Comment by cwolock** [comment]
Pretty close, just need to add some more error handling to the "coverage" metric.

**Comment by cwolock** [comment]
Units tests are done. Still need to add option to count number of NAs, but that's not core functionality.
