### ISSUE TITLE
summary(): make the `name` argument for each list optional

### ISSUE THREAD

**Issue by Avi-Kenny** [Avi-Kenny/simba#40]
Should default to a name of the form [summary stat]_[column name]. For example, if sim$results contains columns alpha and beta, sim %>% summary(mean=list(x=alpha), median=list(x=beta)) would generate columns mean_alpha and median_beta

**Comment by cwolock** [comment]
Made `name` argument optional for all besides `cov` summary. Updated unit tests and docs
