### ISSUE TITLE
Error handling for set_levels()

### ISSUE THREAD

**Issue by Avi-Kenny** [Avi-Kenny/simba#50]
Levels should be one of the following, and set_levels() shoud throw an error if it is not

1) A vector of numbers
`c(1.1, 1.2, 1.3)`

2) A vector of characters:
`c("a", "b", "c")`

3) A named list of vectors (even if the outer list only contains one vector):
```
list(
  "vec 1" = c(1,2,3),
  "vec 2" = c(4,5,6),
)
```

4) A named list of lists (even if the outer list only contains one inner list):
```
list(
  "method 1" = list(type="spline", knots=c(0,1)),
  "method 2" = list(type="regression", knots=NA),
)
```

**Comment by cwolock** [comment]
We ultimately decided on two constraints here. If the user supplies a level that is a list, then (1) each item in the list must be named, and (2) each item in the list must be a list. This basically means there are two allowable level types: lists of lists, and atomic vectors (possibly of length 1)
