### ISSUE TITLE
Catch/handle warnings in addition to errors

### ISSUE THREAD

**Issue by Avi-Kenny** [Avi-Kenny/simba#9]
Catch/handle warnings in addition to errors
- **simba** catches errors and stores them in the sim$errors dataframe. A similar sim$warnings dataframe should be created to catch warnings.
- The message displayed when the simulation is finished should print what percentage of simulations have warnings.

**Comment by cwolock** [comment]
Added this functionality to `run.R`. The returned `sim` object now has a `sim$warnings` dataframe with all returned warnings (possible to have multiple per simulation rep).
